spring:
  application:
    name: test-service

server:
  port: 8080

---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/addki
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop

---

cleanup:
  delay: 10000
