spring:
  application:
    name: test-service
  security:
    user:
      name: user
      password: password

server:
  port: 8080

---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/addki
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---

languages:
  - ko
  - ja
  - zh

cleanup:
  delay: 10000
